//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оказание услуг.
    /// </summary>
    // *** Start programmer edit section *** (ОказаниеУслуг CustomAttributes)

    // *** End programmer edit section *** (ОказаниеУслуг CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОказаниеУслугE", new string[] {
            "Дата as \'Дата\'",
            "Услуги as \'Наименование услуги\'",
            "Услуги.ЗатрВремя as \'Затраченное время\'",
            "Услуги.ЕдВремени as \'Единица времени\'"})]
    [MasterViewDefineAttribute("ОказаниеУслугE", "Услуги", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ОказаниеУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.Услуги fУслуги;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем fРасчетОстВрем;
        
        // *** Start programmer edit section *** (ОказаниеУслуг CustomMembers)

        // *** End programmer edit section *** (ОказаниеУслуг CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Дата CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Дата Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОказаниеУслуг.Дата Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Дата Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Дата Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Дата Set end)
            }
        }
        
        /// <summary>
        /// Оказание услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Услуги CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Услуги CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуги"})]
        [NotNull()]
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.Услуги Услуги
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуги Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуги Get start)
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.Услуги result = this.fУслуги;
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуги Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуги Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуги Set start)
                this.fУслуги = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуги Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуги Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.РасчетОстВрем CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.РасчетОстВрем CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетОстВрем"})]
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем РасчетОстВрем
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Get start)
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем result = this.fРасчетОстВрем;
                // *** Start programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Set start)
                this.fРасчетОстВрем = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.РасчетОстВрем Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОказаниеУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказаниеУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказаниеУслугE", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.ОказаниеУслуг));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОказаниеУслуг.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОказаниеУслуг CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОказаниеУслуг CustomAttributes)
    public class DetailArrayOfОказаниеУслуг : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.DetailArrayOfОказаниеУслуг members)

        // *** End programmer edit section *** (IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.DetailArrayOfОказаниеУслуг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОказаниеУслуг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОказаниеУслуг.
        /// </summary>
        public DetailArrayOfОказаниеУслуг(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем fРасчетОстВрем) : 
                base(typeof(ОказаниеУслуг), ((ICSSoft.STORMNET.DataObject)(fРасчетОстВрем)))
        {
        }
        
        public IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.ОказаниеУслуг this[int index]
        {
            get
            {
                return ((IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.ОказаниеУслуг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.ОказаниеУслуг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
