//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет ост врем.
    /// </summary>
    // *** Start programmer edit section *** (РасчетОстВрем CustomAttributes)

    // *** End programmer edit section *** (РасчетОстВрем CustomAttributes)
    [AutoAltered()]
    [Caption("РасчетВремени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетОстВремE", new string[] {
            "Дата as \'Дата\'",
            "Договор as \'Номер договора\'",
            "Договор.Статус as \'Статус\'",
            "Договор.Длительность as \'Длительность\'",
            "Договор.ЕдВремени as \'Единица времени\'",
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    [AssociatedDetailViewAttribute("РасчетОстВремE", "ОказаниеУслуг", "ОказаниеУслугE", true, "", "Оказание услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РасчетОстВремE", "Договор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("РасчетОстВремL", new string[] {
            "Дата as \'Дата\'",
            "Договор as \'Номер договора\'",
            "Договор.Статус as \'Статус\'",
            "Договор.Длительность as \'Длительность\'",
            "Договор.ЕдВремени as \'Единица времени\'",
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    [MasterViewDefineAttribute("РасчетОстВремL", "Договор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class РасчетОстВрем : ICSSoft.STORMNET.DataObject
    {
        
        private double fДоступно;
        
        private System.DateTime fДата;
        
        private double fИспользовано;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.Договор fДоговор;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.DetailArrayOfОказаниеУслуг fОказаниеУслуг;
        
        // *** Start programmer edit section *** (РасчетОстВрем CustomMembers)

        // *** End programmer edit section *** (РасчетОстВрем CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Дата CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Set end)
            }
        }
        
        /// <summary>
        /// Доступно.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)
        public virtual double Доступно
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get start)
                double result = this.fДоступно;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set start)
                this.fДоступно = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set end)
            }
        }
        
        /// <summary>
        /// Использовано.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)
        public virtual double Использовано
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get start)
                double result = this.fИспользовано;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set start)
                this.fИспользовано = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set end)
            }
        }
        
        /// <summary>
        /// Расчет ост врем.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Договор CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Договор CustomAttributes)
        [PropertyStorage(new string[] {
                "Договор"})]
        [NotNull()]
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Get start)
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Set end)
            }
        }
        
        /// <summary>
        /// Расчет ост врем.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.ОказаниеУслуг CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.ОказаниеУслуг CustomAttributes)
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.DetailArrayOfОказаниеУслуг ОказаниеУслуг
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Get start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Get start)
                if ((this.fОказаниеУслуг == null))
                {
                    this.fОказаниеУслуг = new IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.DetailArrayOfОказаниеУслуг(this);
                }
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.DetailArrayOfОказаниеУслуг result = this.fОказаниеУслуг;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Get end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Set start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Set start)
                this.fОказаниеУслуг = value;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Set end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказаниеУслуг Set end)
            }
        }
        
        // *** Start programmer edit section *** (РасчетОстВрем.Отправить CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (РасчетОстВрем.Отправить method implementation)

            return;
            // *** End programmer edit section *** (РасчетОстВрем.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетОстВремE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетОстВремE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетОстВремE", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем));
                }
            }
            
            /// <summary>
            /// "РасчетОстВремL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетОстВремL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетОстВремL", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov.РасчетОстВрем));
                }
            }
        }
    }
}
